name: shimmer_example
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shimmer:
    path: ..

flutter:
  uses-material-design: true

  assets:
    - assets/images/chevron_right.png
    - assets/images/background.jpg
